image: "python:3.8"

before_script:
  - pip install invoke
  - pip install pelican[Markdown]
  
build:
  script: invoke build
  stage: build
  tags: docker
  artifacts:
    name : "rcenvironment.de-$CI_COMMIT_REF_NAME"
    paths:
      - output/
    expire_in: 1 week