image: "python:3.8"
  
build:
  script: 
    - pip install invoke
    - pip install pelican[Markdown]
    - invoke build
  stage: build
  tags:
    - docker
  artifacts:
    name : "rcenvironment.de-$CI_COMMIT_REF_NAME"
    paths:
      - output/
    expire_in: 1 week
    
build-glpages:
  script: 
    - pip install invoke
    - pip install pelican[Markdown]
    - invoke buildglpages
  stage: build
  tags:
    - docker
  artifacts:
    paths:
      - output/
    expire_in: 1 week
    
pages:
  dependencies:
    - build-glpages
  stage: deploy
  script:
    - mv output public
  tags:
    - docker
  stage: test
  artifacts:
    paths:
      - public